name: Terrform apply
on:
  push:
    paths:
     - 'terraform/**'
     - '.github/workflows/terraform.yml'
jobs:
  terraform:
    environment: qa
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/checkout@v3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - name: setup init
        run: terraform init 
        working-directory: terraform
      - name: setup validate
        run: terraform validate
        working-directory: terraform
      - name: setup plan
        run: terraform plan 
        working-directory: terraform        
      - name: setup apply
        run: terraform apply -auto approve                     
